import type {
  Customer,
  Lead,
  Activity,
  TeamMember,
  Estimate,
  VisionProject,
  Invoice,
  Payment,
} from "./types";

export const demoTeam: TeamMember[] = [
  {
    id: "tm-1",
    name: "Mike Henderson",
    email: "mike@thefinishingtouchllc.com",
    role: "admin",
    created_at: "2024-01-15T08:00:00Z",
  },
  {
    id: "tm-2",
    name: "Jake Henderson",
    email: "jake@thefinishingtouchllc.com",
    role: "manager",
    created_at: "2024-01-15T08:00:00Z",
  },
  {
    id: "tm-3",
    name: "Travis Cole",
    email: "travis@thefinishingtouchllc.com",
    role: "crew",
    created_at: "2024-03-01T08:00:00Z",
  },
];

export const demoCustomers: Customer[] = [
  {
    id: "c-1",
    name: "Steve & Linda Morales",
    email: "smorales@gmail.com",
    phone: "(765) 555-0142",
    address: "4521 Elm Creek Dr",
    city: "Greentown",
    state: "IN",
    zip: "46936",
    service_type: "Concrete Patio",
    source: "Google",
    notes: "Referred by neighbor. Wants stamped concrete patio with fire pit.",
    created_at: "2026-02-10T14:30:00Z",
    updated_at: "2026-03-15T09:00:00Z",
  },
  {
    id: "c-2",
    name: "Brian Whitfield",
    email: "bwhitfield@yahoo.com",
    phone: "(765) 555-0287",
    address: "1102 N Main St",
    city: "Kokomo",
    state: "IN",
    zip: "46901",
    service_type: "Driveway",
    source: "Facebook",
    notes: "Existing driveway is cracked. Wants full tear-out and replace.",
    created_at: "2026-02-18T10:15:00Z",
    updated_at: "2026-03-10T11:00:00Z",
  },
  {
    id: "c-3",
    name: "Rachel Kim",
    email: "rachelk@outlook.com",
    phone: "(317) 555-0391",
    address: "8834 Sycamore Ln",
    city: "Noblesville",
    state: "IN",
    zip: "46060",
    service_type: "Post Frame",
    source: "Website",
    notes: "30x40 post frame garage. Has plans drawn up already.",
    created_at: "2026-01-22T16:45:00Z",
    updated_at: "2026-03-20T14:00:00Z",
  },
  {
    id: "c-4",
    name: "Tom & Diane Marshall",
    email: "tmarshall@gmail.com",
    phone: "(765) 555-0518",
    address: "220 W Sycamore St",
    city: "Greentown",
    state: "IN",
    zip: "46936",
    service_type: "Landscaping",
    source: "Referral",
    notes: "Full backyard renovation. Retaining wall + patio + landscaping.",
    created_at: "2026-03-01T09:00:00Z",
    updated_at: "2026-03-22T10:00:00Z",
  },
  {
    id: "c-5",
    name: "Angela Ross",
    email: "aross@icloud.com",
    phone: "(765) 555-0674",
    address: "7710 County Rd 200 W",
    city: "Russiaville",
    state: "IN",
    zip: "46979",
    service_type: "Curbing",
    source: "Google",
    notes: "Landscape curbing around front beds and driveway border.",
    created_at: "2026-03-05T13:20:00Z",
    updated_at: "2026-03-18T15:30:00Z",
  },
  {
    id: "c-6",
    name: "Derek Johnson",
    email: "djohnson@gmail.com",
    phone: "(765) 555-0823",
    address: "3345 Apperson Way",
    city: "Kokomo",
    state: "IN",
    zip: "46902",
    service_type: "Concrete Patio",
    source: "Facebook",
    notes: "Small 12x12 patio. Budget-conscious.",
    created_at: "2026-03-08T11:00:00Z",
    updated_at: "2026-03-08T11:00:00Z",
  },
  {
    id: "c-7",
    name: "Carla & Jim Nesbitt",
    email: "cnesbitt@gmail.com",
    phone: "(765) 555-0945",
    address: "560 E Carter St",
    city: "Greentown",
    state: "IN",
    zip: "46936",
    service_type: "Driveway",
    source: "Yard Sign",
    notes: "Circular driveway pour. Premium finish.",
    created_at: "2026-02-25T08:30:00Z",
    updated_at: "2026-03-19T16:00:00Z",
  },
  {
    id: "c-8",
    name: "Patricia Okonkwo",
    email: "pokonkwo@hotmail.com",
    phone: "(317) 555-1032",
    address: "1290 Riverfront Pkwy",
    city: "Westfield",
    state: "IN",
    zip: "46074",
    service_type: "Post Frame",
    source: "Website",
    notes: "24x30 workshop with lean-to. Wants it done before summer.",
    created_at: "2026-01-30T15:00:00Z",
    updated_at: "2026-03-12T09:00:00Z",
  },
  {
    id: "c-9",
    name: "Mark Stevenson",
    email: "mstevenson@gmail.com",
    phone: "(765) 555-1188",
    address: "4400 S LaFountain St",
    city: "Kokomo",
    state: "IN",
    zip: "46902",
    service_type: "Concrete Patio",
    source: "Google",
    notes: null,
    created_at: "2026-03-15T10:00:00Z",
    updated_at: "2026-03-15T10:00:00Z",
  },
  {
    id: "c-10",
    name: "Sarah & Dave Henning",
    email: "shenning@gmail.com",
    phone: "(765) 555-1344",
    address: "890 N Buckeye St",
    city: "Greentown",
    state: "IN",
    zip: "46936",
    service_type: "Landscaping",
    source: "Referral",
    notes: "Wants firewood delivery this fall + spring landscaping.",
    created_at: "2026-03-18T14:00:00Z",
    updated_at: "2026-03-20T08:30:00Z",
  },
  {
    id: "c-11",
    name: "Luis Hernandez",
    email: "lhernandez@yahoo.com",
    phone: "(765) 555-1501",
    address: "2200 W Alto Rd",
    city: "Howard County",
    state: "IN",
    zip: "46901",
    service_type: "Post Frame",
    source: "Facebook",
    notes: "40x60 pole barn for equipment storage. Commercial project.",
    created_at: "2026-02-05T09:00:00Z",
    updated_at: "2026-03-21T11:00:00Z",
  },
  {
    id: "c-12",
    name: "Nancy Caldwell",
    email: "ncaldwell@gmail.com",
    phone: "(765) 555-1667",
    address: "615 Taylor St",
    city: "Greentown",
    state: "IN",
    zip: "46936",
    service_type: "Curbing",
    source: "Yard Sign",
    notes: "Curbing + small walkway to front door.",
    created_at: "2026-03-20T16:00:00Z",
    updated_at: "2026-03-20T16:00:00Z",
  },
];

export const demoLeads: Lead[] = [
  {
    id: "l-1",
    customer_id: "c-1",
    status: "in_progress",
    quoted_amount: 8500,
    project_type: "Stamped Concrete Patio",
    project_description:
      "20x16 stamped patio with integrated fire pit. Ashlar slate pattern, desert tan color with dark walnut release.",
    assigned_to: "tm-2",
    created_at: "2026-02-10T14:30:00Z",
    updated_at: "2026-03-15T09:00:00Z",
  },
  {
    id: "l-2",
    customer_id: "c-2",
    status: "quoted",
    quoted_amount: 12200,
    project_type: "Driveway Replacement",
    project_description:
      "Full tear-out of existing 60ft driveway. 6-inch pour with rebar. Broom finish with saw-cut joints.",
    assigned_to: "tm-2",
    created_at: "2026-02-18T10:15:00Z",
    updated_at: "2026-03-10T11:00:00Z",
  },
  {
    id: "l-3",
    customer_id: "c-3",
    status: "booked",
    quoted_amount: 34000,
    project_type: "Post Frame Garage",
    project_description:
      "30x40 post frame with 12ft sidewalls. 2 overhead doors, 1 walk door. Metal roof and siding, concrete floor.",
    assigned_to: "tm-1",
    created_at: "2026-01-22T16:45:00Z",
    updated_at: "2026-03-20T14:00:00Z",
  },
  {
    id: "l-4",
    customer_id: "c-4",
    status: "quoted",
    quoted_amount: 22500,
    project_type: "Backyard Renovation",
    project_description:
      "Retaining wall (45 linear ft), 15x20 patio, landscape beds with mulch and plantings.",
    assigned_to: "tm-2",
    created_at: "2026-03-01T09:00:00Z",
    updated_at: "2026-03-22T10:00:00Z",
  },
  {
    id: "l-5",
    customer_id: "c-5",
    status: "contacted",
    quoted_amount: null,
    project_type: "Landscape Curbing",
    project_description:
      "Curbing around 3 front beds + driveway border. Approximately 120 linear feet.",
    assigned_to: "tm-3",
    created_at: "2026-03-05T13:20:00Z",
    updated_at: "2026-03-18T15:30:00Z",
  },
  {
    id: "l-6",
    customer_id: "c-6",
    status: "new",
    quoted_amount: null,
    project_type: "Concrete Patio",
    project_description:
      "12x12 basic broom finish patio off back sliding door.",
    assigned_to: null,
    created_at: "2026-03-08T11:00:00Z",
    updated_at: "2026-03-08T11:00:00Z",
  },
  {
    id: "l-7",
    customer_id: "c-7",
    status: "in_progress",
    quoted_amount: 18500,
    project_type: "Circular Driveway",
    project_description:
      "Circular driveway with exposed aggregate finish. Includes turnaround area. ~1800 sq ft total.",
    assigned_to: "tm-1",
    created_at: "2026-02-25T08:30:00Z",
    updated_at: "2026-03-19T16:00:00Z",
  },
  {
    id: "l-8",
    customer_id: "c-8",
    status: "completed",
    quoted_amount: 28000,
    project_type: "Post Frame Workshop",
    project_description:
      "24x30 workshop with 8ft lean-to. Insulated, wired for 200 amp service. Concrete floor with drain.",
    assigned_to: "tm-1",
    created_at: "2026-01-30T15:00:00Z",
    updated_at: "2026-03-12T09:00:00Z",
  },
  {
    id: "l-9",
    customer_id: "c-9",
    status: "new",
    quoted_amount: null,
    project_type: "Concrete Patio",
    project_description: "Interested in a patio. No details yet.",
    assigned_to: null,
    created_at: "2026-03-15T10:00:00Z",
    updated_at: "2026-03-15T10:00:00Z",
  },
  {
    id: "l-10",
    customer_id: "c-10",
    status: "new",
    quoted_amount: null,
    project_type: "Landscaping",
    project_description:
      "Spring landscaping package + firewood delivery for fall.",
    assigned_to: null,
    created_at: "2026-03-18T14:00:00Z",
    updated_at: "2026-03-20T08:30:00Z",
  },
  {
    id: "l-11",
    customer_id: "c-11",
    status: "booked",
    quoted_amount: 52000,
    project_type: "Commercial Pole Barn",
    project_description:
      "40x60 pole barn for equipment storage. 14ft sidewalls, 2 large overhead doors, gravel approach.",
    assigned_to: "tm-1",
    created_at: "2026-02-05T09:00:00Z",
    updated_at: "2026-03-21T11:00:00Z",
  },
  {
    id: "l-12",
    customer_id: "c-12",
    status: "contacted",
    quoted_amount: null,
    project_type: "Curbing + Walkway",
    project_description:
      "Decorative curbing around beds and new concrete walkway to front door.",
    assigned_to: "tm-3",
    created_at: "2026-03-20T16:00:00Z",
    updated_at: "2026-03-20T16:00:00Z",
  },
  {
    id: "l-13",
    customer_id: "c-2",
    status: "lost",
    quoted_amount: 4500,
    project_type: "Sidewalk Repair",
    project_description:
      "Previous inquiry for sidewalk. Went with another contractor.",
    assigned_to: "tm-2",
    created_at: "2025-11-10T09:00:00Z",
    updated_at: "2025-12-15T14:00:00Z",
  },
];

export const demoActivities: Activity[] = [
  {
    id: "a-1",
    lead_id: "l-1",
    customer_id: "c-1",
    type: "call",
    description:
      "Initial call with Steve. Discussed stamped patio options and fire pit placement.",
    created_by: "tm-2",
    created_at: "2026-02-10T14:30:00Z",
  },
  {
    id: "a-2",
    lead_id: "l-1",
    customer_id: "c-1",
    type: "quote",
    description: "Sent quote for $8,500 — stamped patio with fire pit.",
    created_by: "tm-2",
    created_at: "2026-02-15T10:00:00Z",
  },
  {
    id: "a-3",
    lead_id: "l-1",
    customer_id: "c-1",
    type: "note",
    description: "Customer approved quote. Deposit received. Scheduled for March.",
    created_by: "tm-2",
    created_at: "2026-02-20T11:30:00Z",
  },
  {
    id: "a-4",
    lead_id: "l-1",
    customer_id: "c-1",
    type: "note",
    description: "Started excavation. Weather looks good for the week.",
    created_by: "tm-1",
    created_at: "2026-03-10T08:00:00Z",
  },
  {
    id: "a-5",
    lead_id: "l-2",
    customer_id: "c-2",
    type: "call",
    description: "Brian called about driveway replacement. Scheduled site visit.",
    created_by: "tm-2",
    created_at: "2026-02-18T10:15:00Z",
  },
  {
    id: "a-6",
    lead_id: "l-2",
    customer_id: "c-2",
    type: "note",
    description: "Site visit completed. Measured 60ft driveway, noted drain issues.",
    created_by: "tm-2",
    created_at: "2026-02-22T14:00:00Z",
  },
  {
    id: "a-7",
    lead_id: "l-2",
    customer_id: "c-2",
    type: "quote",
    description: "Sent quote for $12,200 — driveway tear-out and replace.",
    created_by: "tm-2",
    created_at: "2026-03-01T09:30:00Z",
  },
  {
    id: "a-8",
    lead_id: "l-3",
    customer_id: "c-3",
    type: "email",
    description: "Rachel emailed plans for 30x40 post frame. Reviewed specs.",
    created_by: "tm-1",
    created_at: "2026-01-22T16:45:00Z",
  },
  {
    id: "a-9",
    lead_id: "l-3",
    customer_id: "c-3",
    type: "quote",
    description: "Sent detailed quote for $34,000 — post frame garage.",
    created_by: "tm-1",
    created_at: "2026-02-01T10:00:00Z",
  },
  {
    id: "a-10",
    lead_id: "l-3",
    customer_id: "c-3",
    type: "payment",
    description: "Deposit received — $10,000. Project booked for April.",
    created_by: "tm-1",
    created_at: "2026-03-15T11:00:00Z",
  },
  {
    id: "a-11",
    lead_id: "l-5",
    customer_id: "c-5",
    type: "call",
    description: "Angela called about curbing. Wants to match neighbor's style.",
    created_by: "tm-3",
    created_at: "2026-03-05T13:20:00Z",
  },
  {
    id: "a-12",
    lead_id: "l-5",
    customer_id: "c-5",
    type: "note",
    description: "Scheduled site visit for Friday to measure and pick colors.",
    created_by: "tm-3",
    created_at: "2026-03-12T09:00:00Z",
  },
  {
    id: "a-13",
    lead_id: "l-7",
    customer_id: "c-7",
    type: "quote",
    description: "Sent quote for $18,500 — circular driveway, exposed aggregate.",
    created_by: "tm-1",
    created_at: "2026-03-01T14:00:00Z",
  },
  {
    id: "a-14",
    lead_id: "l-7",
    customer_id: "c-7",
    type: "payment",
    description: "Deposit received — $5,000. Started forming.",
    created_by: "tm-1",
    created_at: "2026-03-10T08:30:00Z",
  },
  {
    id: "a-15",
    lead_id: "l-8",
    customer_id: "c-8",
    type: "note",
    description: "Project complete. Final inspection passed. Customer very happy.",
    created_by: "tm-1",
    created_at: "2026-03-12T09:00:00Z",
  },
  {
    id: "a-16",
    lead_id: "l-8",
    customer_id: "c-8",
    type: "payment",
    description: "Final payment received — $18,000. Project fully paid.",
    created_by: "tm-1",
    created_at: "2026-03-12T15:00:00Z",
  },
  {
    id: "a-17",
    lead_id: "l-11",
    customer_id: "c-11",
    type: "call",
    description:
      "Luis called about large pole barn. Discussed specs and timeline.",
    created_by: "tm-1",
    created_at: "2026-02-05T09:00:00Z",
  },
  {
    id: "a-18",
    lead_id: "l-11",
    customer_id: "c-11",
    type: "quote",
    description: "Sent quote for $52,000 — 40x60 commercial pole barn.",
    created_by: "tm-1",
    created_at: "2026-02-15T10:00:00Z",
  },
  {
    id: "a-19",
    lead_id: "l-11",
    customer_id: "c-11",
    type: "payment",
    description: "Deposit received — $15,000. Booked for late April start.",
    created_by: "tm-1",
    created_at: "2026-03-01T11:00:00Z",
  },
  {
    id: "a-20",
    lead_id: "l-4",
    customer_id: "c-4",
    type: "call",
    description: "Diane called about backyard renovation. Wants full package.",
    created_by: "tm-2",
    created_at: "2026-03-01T09:00:00Z",
  },
  {
    id: "a-21",
    lead_id: "l-4",
    customer_id: "c-4",
    type: "quote",
    description:
      "Sent quote for $22,500 — retaining wall, patio, landscaping.",
    created_by: "tm-2",
    created_at: "2026-03-15T14:00:00Z",
  },
  {
    id: "a-22",
    lead_id: "l-4",
    customer_id: "c-4",
    type: "email",
    description: "Follow-up email sent. Waiting for approval on quote.",
    created_by: "tm-2",
    created_at: "2026-03-22T10:00:00Z",
  },
];

export const demoEstimates: Estimate[] = [
  {
    id: "est-1",
    customer_id: "c-1",
    customer_name: "Steve & Linda Morales",
    status: "accepted",
    project_type: "Stamped Concrete",
    dimensions: { length: 20, width: 16, square_footage: 320 },
    materials: ["Ashlar Slate"],
    complexity: "moderate",
    options: {
      demolition: false,
      grading: true,
      sealing: true,
      color_stain: "Desert Tan with Dark Walnut Release",
    },
    line_items: [
      {
        id: "li-1",
        category: "material",
        description: "Concrete (6-sack mix) — 320 sq ft at 4\" depth",
        quantity: 4,
        unit: "yards",
        unit_cost: 165,
        total: 660,
      },
      {
        id: "li-2",
        category: "material",
        description: "Ashlar Slate stamp mats & color hardener",
        quantity: 1,
        unit: "set",
        unit_cost: 480,
        total: 480,
      },
      {
        id: "li-3",
        category: "material",
        description: "Rebar & mesh reinforcement",
        quantity: 320,
        unit: "sq ft",
        unit_cost: 1.25,
        total: 400,
      },
      {
        id: "li-4",
        category: "material",
        description: "Acrylic sealer (2 coats)",
        quantity: 5,
        unit: "gallons",
        unit_cost: 45,
        total: 225,
      },
      {
        id: "li-5",
        category: "labor",
        description: "Excavation & grading",
        quantity: 8,
        unit: "hours",
        unit_cost: 65,
        total: 520,
      },
      {
        id: "li-6",
        category: "labor",
        description: "Forming, pouring & stamping",
        quantity: 24,
        unit: "hours",
        unit_cost: 65,
        total: 1560,
      },
      {
        id: "li-7",
        category: "labor",
        description: "Finishing & sealing",
        quantity: 8,
        unit: "hours",
        unit_cost: 65,
        total: 520,
      },
      {
        id: "li-8",
        category: "equipment",
        description: "Skid steer rental (1 day)",
        quantity: 1,
        unit: "day",
        unit_cost: 350,
        total: 350,
      },
      {
        id: "li-9",
        category: "equipment",
        description: "Concrete pump truck",
        quantity: 1,
        unit: "trip",
        unit_cost: 450,
        total: 450,
      },
    ],
    subtotal: 5165,
    margin: 1291,
    total: 6456,
    timeline: "3-4 days on site, weather permitting",
    notes:
      "Includes fire pit cutout. Customer providing fire pit insert. Color samples approved.",
    created_at: "2026-02-14T10:00:00Z",
    updated_at: "2026-02-20T11:30:00Z",
  },
  {
    id: "est-2",
    customer_id: "c-2",
    customer_name: "Brian Whitfield",
    status: "sent",
    project_type: "Concrete Driveway",
    dimensions: { length: 60, width: 12, depth: 6, square_footage: 720 },
    materials: ["Broom Finish"],
    complexity: "moderate",
    options: {
      demolition: true,
      grading: true,
      sealing: false,
      color_stain: "",
    },
    line_items: [
      {
        id: "li-10",
        category: "material",
        description: "Concrete (6-sack mix) — 720 sq ft at 6\" depth",
        quantity: 14,
        unit: "yards",
        unit_cost: 165,
        total: 2310,
      },
      {
        id: "li-11",
        category: "material",
        description: "Rebar grid (#4 rebar, 18\" OC)",
        quantity: 720,
        unit: "sq ft",
        unit_cost: 1.5,
        total: 1080,
      },
      {
        id: "li-12",
        category: "labor",
        description: "Demolition & haul-off of existing driveway",
        quantity: 16,
        unit: "hours",
        unit_cost: 65,
        total: 1040,
      },
      {
        id: "li-13",
        category: "labor",
        description: "Grading & compaction",
        quantity: 8,
        unit: "hours",
        unit_cost: 65,
        total: 520,
      },
      {
        id: "li-14",
        category: "labor",
        description: "Forming, pouring & finishing",
        quantity: 24,
        unit: "hours",
        unit_cost: 65,
        total: 1560,
      },
      {
        id: "li-15",
        category: "equipment",
        description: "Skid steer + dump trailer (2 days)",
        quantity: 2,
        unit: "days",
        unit_cost: 450,
        total: 900,
      },
      {
        id: "li-16",
        category: "equipment",
        description: "Concrete pump truck",
        quantity: 1,
        unit: "trip",
        unit_cost: 450,
        total: 450,
      },
    ],
    subtotal: 7860,
    margin: 1965,
    total: 9825,
    timeline: "4-5 days including demo and cure time",
    notes: "Drain issue noted at site visit — may need to adjust grade.",
    created_at: "2026-03-01T09:30:00Z",
    updated_at: "2026-03-01T09:30:00Z",
  },
  {
    id: "est-3",
    customer_id: "c-5",
    customer_name: "Angela Ross",
    status: "draft",
    project_type: "Decorative Curbing",
    dimensions: { linear_feet: 120 },
    materials: ["Mower Edge"],
    complexity: "easy",
    options: {
      demolition: false,
      grading: false,
      sealing: true,
      color_stain: "Charcoal Gray",
    },
    line_items: [
      {
        id: "li-17",
        category: "material",
        description: "Curbing mix & color additive",
        quantity: 120,
        unit: "linear ft",
        unit_cost: 2.5,
        total: 300,
      },
      {
        id: "li-18",
        category: "material",
        description: "Sealer",
        quantity: 2,
        unit: "gallons",
        unit_cost: 45,
        total: 90,
      },
      {
        id: "li-19",
        category: "labor",
        description: "Layout, extrude & finish curbing",
        quantity: 10,
        unit: "hours",
        unit_cost: 65,
        total: 650,
      },
      {
        id: "li-20",
        category: "equipment",
        description: "Curbing machine",
        quantity: 1,
        unit: "day",
        unit_cost: 200,
        total: 200,
      },
    ],
    subtotal: 1240,
    margin: 310,
    total: 1550,
    timeline: "1 day on site",
    notes: "Customer wants to match neighbor's curbing style.",
    created_at: "2026-03-18T14:00:00Z",
    updated_at: "2026-03-18T14:00:00Z",
  },
  {
    id: "est-4",
    customer_id: "c-4",
    customer_name: "Tom & Diane Marshall",
    status: "sent",
    project_type: "Landscaping",
    dimensions: { square_footage: 2400 },
    materials: ["Retaining Walls", "Mulch Beds", "Plantings & Shrubs"],
    complexity: "difficult",
    options: {
      demolition: false,
      grading: true,
      sealing: false,
      color_stain: "",
    },
    line_items: [
      {
        id: "li-21",
        category: "material",
        description: "Retaining wall blocks (45 linear ft, 3 courses)",
        quantity: 540,
        unit: "blocks",
        unit_cost: 4.5,
        total: 2430,
      },
      {
        id: "li-22",
        category: "material",
        description: "Mulch (hardwood)",
        quantity: 15,
        unit: "yards",
        unit_cost: 55,
        total: 825,
      },
      {
        id: "li-23",
        category: "material",
        description: "Plants, shrubs & perennials",
        quantity: 1,
        unit: "lot",
        unit_cost: 2800,
        total: 2800,
      },
      {
        id: "li-24",
        category: "material",
        description: "Landscape fabric & edging",
        quantity: 1,
        unit: "lot",
        unit_cost: 350,
        total: 350,
      },
      {
        id: "li-25",
        category: "labor",
        description: "Grading & site prep",
        quantity: 16,
        unit: "hours",
        unit_cost: 65,
        total: 1040,
      },
      {
        id: "li-26",
        category: "labor",
        description: "Retaining wall construction",
        quantity: 32,
        unit: "hours",
        unit_cost: 65,
        total: 2080,
      },
      {
        id: "li-27",
        category: "labor",
        description: "Planting & mulching",
        quantity: 16,
        unit: "hours",
        unit_cost: 65,
        total: 1040,
      },
      {
        id: "li-28",
        category: "equipment",
        description: "Mini excavator rental (2 days)",
        quantity: 2,
        unit: "days",
        unit_cost: 400,
        total: 800,
      },
    ],
    subtotal: 11365,
    margin: 2841,
    total: 14206,
    timeline: "7-10 days depending on weather",
    notes:
      "Full backyard renovation. Includes 15x20 patio area prep (patio quoted separately).",
    created_at: "2026-03-15T14:00:00Z",
    updated_at: "2026-03-15T14:00:00Z",
  },
];

export const demoVisionProjects: VisionProject[] = [
  {
    id: "vis-1",
    customer_id: "c-1",
    customer_name: "Steve & Linda Morales",
    original_image_url: "/demo/vision-backyard-before.jpg",
    service_type: "Stamped Concrete",
    description: "Stamped concrete patio with fire pit in backyard",
    iterations: [
      {
        id: "vi-1",
        image_url: "/demo/vision-backyard-after-1.jpg",
        prompt_used:
          "Professional architectural visualization of a stamped concrete patio with ashlar slate pattern and integrated fire pit installed in this backyard space.",
        add_on: null,
        created_at: "2026-02-12T10:00:00Z",
      },
      {
        id: "vi-2",
        image_url: "/demo/vision-backyard-after-2.jpg",
        prompt_used:
          "Same patio visualization with landscape lighting along the edges and pathway lights.",
        add_on: "Landscape lighting",
        created_at: "2026-02-12T10:15:00Z",
      },
    ],
    created_at: "2026-02-12T10:00:00Z",
    updated_at: "2026-02-12T10:15:00Z",
  },
  {
    id: "vis-2",
    customer_id: "c-4",
    customer_name: "Tom & Diane Marshall",
    original_image_url: "/demo/vision-landscape-before.jpg",
    service_type: "Landscaping",
    description: "Full backyard renovation with retaining wall and patio",
    iterations: [
      {
        id: "vi-3",
        image_url: "/demo/vision-landscape-after-1.jpg",
        prompt_used:
          "Professional landscape design visualization showing retaining wall, patio area, and garden beds in this backyard.",
        add_on: null,
        created_at: "2026-03-02T14:00:00Z",
      },
    ],
    created_at: "2026-03-02T14:00:00Z",
    updated_at: "2026-03-02T14:00:00Z",
  },
];

// ── Module 4: Invoices & Payments ──

export const demoInvoices: Invoice[] = [
  {
    id: "inv-1",
    customer_id: "c-8",
    lead_id: "l-8",
    estimate_id: "est-1",
    invoice_number: "TFT-0001",
    status: "paid",
    line_items: [
      {
        id: "ili-1",
        description: "Post Frame Workshop — 24x30 with lean-to",
        quantity: 1,
        unit_price: 28000,
        total: 28000,
      },
    ],
    subtotal: 28000,
    tax_rate: 0.07,
    tax_amount: 1960,
    total: 29960,
    notes: "Final payment for completed workshop build. Thank you for your business!",
    due_date: "2026-03-15T00:00:00Z",
    sent_at: "2026-03-12T10:00:00Z",
    viewed_at: "2026-03-12T14:22:00Z",
    paid_at: "2026-03-12T15:00:00Z",
    payment_method: "stripe",
    stripe_payment_intent_id: "pi_demo_001",
    created_at: "2026-03-12T09:30:00Z",
    updated_at: "2026-03-12T15:00:00Z",
  },
  {
    id: "inv-2",
    customer_id: "c-3",
    lead_id: "l-3",
    estimate_id: null,
    invoice_number: "TFT-0002",
    status: "sent",
    line_items: [
      {
        id: "ili-2",
        description: "Post Frame Garage 30x40 — Deposit",
        quantity: 1,
        unit_price: 10000,
        total: 10000,
      },
    ],
    subtotal: 10000,
    tax_rate: 0.07,
    tax_amount: 700,
    total: 10700,
    notes: "50% deposit required before project start. Balance due upon completion.",
    due_date: "2026-04-01T00:00:00Z",
    sent_at: "2026-03-20T09:00:00Z",
    viewed_at: null,
    paid_at: null,
    payment_method: null,
    stripe_payment_intent_id: null,
    created_at: "2026-03-20T08:45:00Z",
    updated_at: "2026-03-20T09:00:00Z",
  },
  {
    id: "inv-3",
    customer_id: "c-7",
    lead_id: "l-7",
    estimate_id: null,
    invoice_number: "TFT-0003",
    status: "viewed",
    line_items: [
      {
        id: "ili-3",
        description: "Circular Driveway — Exposed aggregate finish",
        quantity: 1800,
        unit_price: 8.5,
        total: 15300,
      },
      {
        id: "ili-4",
        description: "Turnaround area — additional forming & pour",
        quantity: 1,
        unit_price: 3200,
        total: 3200,
      },
    ],
    subtotal: 18500,
    tax_rate: 0.07,
    tax_amount: 1295,
    total: 19795,
    notes: "Balance due for circular driveway project. Deposit of $5,000 already received.",
    due_date: "2026-04-05T00:00:00Z",
    sent_at: "2026-03-19T16:30:00Z",
    viewed_at: "2026-03-20T08:15:00Z",
    paid_at: null,
    payment_method: null,
    stripe_payment_intent_id: null,
    created_at: "2026-03-19T16:00:00Z",
    updated_at: "2026-03-20T08:15:00Z",
  },
  {
    id: "inv-4",
    customer_id: "c-11",
    lead_id: "l-11",
    estimate_id: null,
    invoice_number: "TFT-0004",
    status: "overdue",
    line_items: [
      {
        id: "ili-5",
        description: "Commercial Pole Barn 40x60 — Deposit (30%)",
        quantity: 1,
        unit_price: 15600,
        total: 15600,
      },
    ],
    subtotal: 15600,
    tax_rate: 0.07,
    tax_amount: 1092,
    total: 16692,
    notes: "Deposit invoice for 40x60 commercial pole barn. Please remit payment to begin material ordering.",
    due_date: "2026-03-15T00:00:00Z",
    sent_at: "2026-03-05T10:00:00Z",
    viewed_at: "2026-03-05T18:30:00Z",
    paid_at: null,
    payment_method: null,
    stripe_payment_intent_id: null,
    created_at: "2026-03-05T09:30:00Z",
    updated_at: "2026-03-05T18:30:00Z",
  },
  {
    id: "inv-5",
    customer_id: "c-1",
    lead_id: "l-1",
    estimate_id: "est-1",
    invoice_number: "TFT-0005",
    status: "partial",
    line_items: [
      {
        id: "ili-6",
        description: "Stamped Concrete Patio — Ashlar Slate pattern, 320 sq ft",
        quantity: 320,
        unit_price: 18.75,
        total: 6000,
      },
      {
        id: "ili-7",
        description: "Fire pit cutout & prep",
        quantity: 1,
        unit_price: 1200,
        total: 1200,
      },
      {
        id: "ili-8",
        description: "Acrylic sealer (2 coats)",
        quantity: 1,
        unit_price: 800,
        total: 800,
      },
    ],
    subtotal: 8000,
    tax_rate: 0.07,
    tax_amount: 560,
    total: 8560,
    notes: "Deposit of $3,000 received. Remaining balance due upon completion.",
    due_date: "2026-03-30T00:00:00Z",
    sent_at: "2026-03-10T11:00:00Z",
    viewed_at: "2026-03-10T14:00:00Z",
    paid_at: null,
    payment_method: null,
    stripe_payment_intent_id: null,
    created_at: "2026-03-10T10:30:00Z",
    updated_at: "2026-03-10T14:00:00Z",
  },
  {
    id: "inv-6",
    customer_id: "c-2",
    lead_id: "l-2",
    estimate_id: "est-2",
    invoice_number: "TFT-0006",
    status: "draft",
    line_items: [
      {
        id: "ili-9",
        description: "Driveway Tear-out & Replace — 720 sq ft, 6\" pour",
        quantity: 1,
        unit_price: 12200,
        total: 12200,
      },
    ],
    subtotal: 12200,
    tax_rate: 0.07,
    tax_amount: 854,
    total: 13054,
    notes: "Pending customer approval of quote. Draft invoice prepared.",
    due_date: "2026-04-15T00:00:00Z",
    sent_at: null,
    viewed_at: null,
    paid_at: null,
    payment_method: null,
    stripe_payment_intent_id: null,
    created_at: "2026-03-22T14:00:00Z",
    updated_at: "2026-03-22T14:00:00Z",
  },
];

export const demoPayments: Payment[] = [
  {
    id: "pay-1",
    invoice_id: "inv-1",
    amount: 29960,
    method: "stripe",
    stripe_payment_id: "ch_demo_001",
    notes: "Full payment via Stripe",
    created_at: "2026-03-12T15:00:00Z",
  },
  {
    id: "pay-2",
    invoice_id: "inv-5",
    amount: 3000,
    method: "check",
    stripe_payment_id: null,
    notes: "Deposit — check #4821",
    created_at: "2026-03-10T16:00:00Z",
  },
];
