import type {
  Customer,
  Lead,
  Activity,
  TeamMember,
  Estimate,
  VisionProject,
  Invoice,
  Payment,
  AIAgent,
  AgentAction,
  MarketingContact,
  EmailTemplate,
  Campaign,
  Automation,
  AvailabilityRule,
  CalendarEvent,
  JobWalk,
  JobWalkPhoto,
} from "./types";

export const demoTeam: TeamMember[] = [
  {
    id: "tm-1",
    name: "Mike Henderson",
    email: "mike@thefinishingtouchllc.com",
    role: "admin",
    phone: null,
    color: "#3b82f6",
    notification_email: null,
    is_active: true,
    created_at: "2024-01-15T08:00:00Z",
  },
  {
    id: "tm-2",
    name: "Jake Henderson",
    email: "jake@thefinishingtouchllc.com",
    role: "manager",
    phone: null,
    color: "#10b981",
    notification_email: null,
    is_active: true,
    created_at: "2024-01-15T08:00:00Z",
  },
  {
    id: "tm-3",
    name: "Travis Cole",
    email: "travis@thefinishingtouchllc.com",
    role: "crew",
    phone: null,
    color: "#f59e0b",
    notification_email: null,
    is_active: true,
    created_at: "2024-03-01T08:00:00Z",
  },
];

export const demoCustomers: Customer[] = [
  {
    id: "c-1",
    name: "Steve & Linda Morales",
    email: "smorales@gmail.com",
    phone: "(765) 555-0142",
    address: "4521 Elm Creek Dr",
    city: "Greentown",
    state: "IN",
    zip: "46936",
    service_type: "Concrete Patio",
    source: "Google",
    notes: "Referred by neighbor. Wants stamped concrete patio with fire pit.",
    created_at: "2026-02-10T14:30:00Z",
    updated_at: "2026-03-15T09:00:00Z",
  },
  {
    id: "c-2",
    name: "Brian Whitfield",
    email: "bwhitfield@yahoo.com",
    phone: "(765) 555-0287",
    address: "1102 N Main St",
    city: "Kokomo",
    state: "IN",
    zip: "46901",
    service_type: "Driveway",
    source: "Facebook",
    notes: "Existing driveway is cracked. Wants full tear-out and replace.",
    created_at: "2026-02-18T10:15:00Z",
    updated_at: "2026-03-10T11:00:00Z",
  },
  {
    id: "c-3",
    name: "Rachel Kim",
    email: "rachelk@outlook.com",
    phone: "(317) 555-0391",
    address: "8834 Sycamore Ln",
    city: "Noblesville",
    state: "IN",
    zip: "46060",
    service_type: "Post Frame",
    source: "Website",
    notes: "30x40 post frame garage. Has plans drawn up already.",
    created_at: "2026-01-22T16:45:00Z",
    updated_at: "2026-03-20T14:00:00Z",
  },
  {
    id: "c-4",
    name: "Tom & Diane Marshall",
    email: "tmarshall@gmail.com",
    phone: "(765) 555-0518",
    address: "220 W Sycamore St",
    city: "Greentown",
    state: "IN",
    zip: "46936",
    service_type: "Landscaping",
    source: "Referral",
    notes: "Full backyard renovation. Retaining wall + patio + landscaping.",
    created_at: "2026-03-01T09:00:00Z",
    updated_at: "2026-03-22T10:00:00Z",
  },
  {
    id: "c-5",
    name: "Angela Ross",
    email: "aross@icloud.com",
    phone: "(765) 555-0674",
    address: "7710 County Rd 200 W",
    city: "Russiaville",
    state: "IN",
    zip: "46979",
    service_type: "Curbing",
    source: "Google",
    notes: "Landscape curbing around front beds and driveway border.",
    created_at: "2026-03-05T13:20:00Z",
    updated_at: "2026-03-18T15:30:00Z",
  },
  {
    id: "c-6",
    name: "Derek Johnson",
    email: "djohnson@gmail.com",
    phone: "(765) 555-0823",
    address: "3345 Apperson Way",
    city: "Kokomo",
    state: "IN",
    zip: "46902",
    service_type: "Concrete Patio",
    source: "Facebook",
    notes: "Small 12x12 patio. Budget-conscious.",
    created_at: "2026-03-08T11:00:00Z",
    updated_at: "2026-03-08T11:00:00Z",
  },
  {
    id: "c-7",
    name: "Carla & Jim Nesbitt",
    email: "cnesbitt@gmail.com",
    phone: "(765) 555-0945",
    address: "560 E Carter St",
    city: "Greentown",
    state: "IN",
    zip: "46936",
    service_type: "Driveway",
    source: "Yard Sign",
    notes: "Circular driveway pour. Premium finish.",
    created_at: "2026-02-25T08:30:00Z",
    updated_at: "2026-03-19T16:00:00Z",
  },
  {
    id: "c-8",
    name: "Patricia Okonkwo",
    email: "pokonkwo@hotmail.com",
    phone: "(317) 555-1032",
    address: "1290 Riverfront Pkwy",
    city: "Westfield",
    state: "IN",
    zip: "46074",
    service_type: "Post Frame",
    source: "Website",
    notes: "24x30 workshop with lean-to. Wants it done before summer.",
    created_at: "2026-01-30T15:00:00Z",
    updated_at: "2026-03-12T09:00:00Z",
  },
  {
    id: "c-9",
    name: "Mark Stevenson",
    email: "mstevenson@gmail.com",
    phone: "(765) 555-1188",
    address: "4400 S LaFountain St",
    city: "Kokomo",
    state: "IN",
    zip: "46902",
    service_type: "Concrete Patio",
    source: "Google",
    notes: null,
    created_at: "2026-03-15T10:00:00Z",
    updated_at: "2026-03-15T10:00:00Z",
  },
  {
    id: "c-10",
    name: "Sarah & Dave Henning",
    email: "shenning@gmail.com",
    phone: "(765) 555-1344",
    address: "890 N Buckeye St",
    city: "Greentown",
    state: "IN",
    zip: "46936",
    service_type: "Landscaping",
    source: "Referral",
    notes: "Wants firewood delivery this fall + spring landscaping.",
    created_at: "2026-03-18T14:00:00Z",
    updated_at: "2026-03-20T08:30:00Z",
  },
  {
    id: "c-11",
    name: "Luis Hernandez",
    email: "lhernandez@yahoo.com",
    phone: "(765) 555-1501",
    address: "2200 W Alto Rd",
    city: "Howard County",
    state: "IN",
    zip: "46901",
    service_type: "Post Frame",
    source: "Facebook",
    notes: "40x60 pole barn for equipment storage. Commercial project.",
    created_at: "2026-02-05T09:00:00Z",
    updated_at: "2026-03-21T11:00:00Z",
  },
  {
    id: "c-12",
    name: "Nancy Caldwell",
    email: "ncaldwell@gmail.com",
    phone: "(765) 555-1667",
    address: "615 Taylor St",
    city: "Greentown",
    state: "IN",
    zip: "46936",
    service_type: "Curbing",
    source: "Yard Sign",
    notes: "Curbing + small walkway to front door.",
    created_at: "2026-03-20T16:00:00Z",
    updated_at: "2026-03-20T16:00:00Z",
  },
];

export const demoLeads: Lead[] = [
  {
    id: "l-1",
    customer_id: "c-1",
    status: "in_progress",
    quoted_amount: 8500,
    project_type: "Stamped Concrete Patio",
    project_description:
      "20x16 stamped patio with integrated fire pit. Ashlar slate pattern, desert tan color with dark walnut release.",
    assigned_to: "tm-2",
    vapi_call_id: null,
    call_transcript_url: null,
    call_duration_seconds: null,
    created_at: "2026-02-10T14:30:00Z",
    updated_at: "2026-03-15T09:00:00Z",
  },
  {
    id: "l-2",
    customer_id: "c-2",
    status: "quoted",
    quoted_amount: 12200,
    project_type: "Driveway Replacement",
    project_description:
      "Full tear-out of existing 60ft driveway. 6-inch pour with rebar. Broom finish with saw-cut joints.",
    assigned_to: "tm-2",
    vapi_call_id: null,
    call_transcript_url: null,
    call_duration_seconds: null,
    created_at: "2026-02-18T10:15:00Z",
    updated_at: "2026-03-10T11:00:00Z",
  },
  {
    id: "l-3",
    customer_id: "c-3",
    status: "booked",
    quoted_amount: 34000,
    project_type: "Post Frame Garage",
    project_description:
      "30x40 post frame with 12ft sidewalls. 2 overhead doors, 1 walk door. Metal roof and siding, concrete floor.",
    assigned_to: "tm-1",
    vapi_call_id: null,
    call_transcript_url: null,
    call_duration_seconds: null,
    created_at: "2026-01-22T16:45:00Z",
    updated_at: "2026-03-20T14:00:00Z",
  },
  {
    id: "l-4",
    customer_id: "c-4",
    status: "quoted",
    quoted_amount: 22500,
    project_type: "Backyard Renovation",
    project_description:
      "Retaining wall (45 linear ft), 15x20 patio, landscape beds with mulch and plantings.",
    assigned_to: "tm-2",
    vapi_call_id: null,
    call_transcript_url: null,
    call_duration_seconds: null,
    created_at: "2026-03-01T09:00:00Z",
    updated_at: "2026-03-22T10:00:00Z",
  },
  {
    id: "l-5",
    customer_id: "c-5",
    status: "contacted",
    quoted_amount: null,
    project_type: "Landscape Curbing",
    project_description:
      "Curbing around 3 front beds + driveway border. Approximately 120 linear feet.",
    assigned_to: "tm-3",
    vapi_call_id: null,
    call_transcript_url: null,
    call_duration_seconds: null,
    created_at: "2026-03-05T13:20:00Z",
    updated_at: "2026-03-18T15:30:00Z",
  },
  {
    id: "l-6",
    customer_id: "c-6",
    status: "new",
    quoted_amount: null,
    project_type: "Concrete Patio",
    project_description:
      "12x12 basic broom finish patio off back sliding door.",
    assigned_to: null,
    vapi_call_id: null,
    call_transcript_url: null,
    call_duration_seconds: null,
    created_at: "2026-03-08T11:00:00Z",
    updated_at: "2026-03-08T11:00:00Z",
  },
  {
    id: "l-7",
    customer_id: "c-7",
    status: "in_progress",
    quoted_amount: 18500,
    project_type: "Circular Driveway",
    project_description:
      "Circular driveway with exposed aggregate finish. Includes turnaround area. ~1800 sq ft total.",
    assigned_to: "tm-1",
    vapi_call_id: null,
    call_transcript_url: null,
    call_duration_seconds: null,
    created_at: "2026-02-25T08:30:00Z",
    updated_at: "2026-03-19T16:00:00Z",
  },
  {
    id: "l-8",
    customer_id: "c-8",
    status: "completed",
    quoted_amount: 28000,
    project_type: "Post Frame Workshop",
    project_description:
      "24x30 workshop with 8ft lean-to. Insulated, wired for 200 amp service. Concrete floor with drain.",
    assigned_to: "tm-1",
    vapi_call_id: null,
    call_transcript_url: null,
    call_duration_seconds: null,
    created_at: "2026-01-30T15:00:00Z",
    updated_at: "2026-03-12T09:00:00Z",
  },
  {
    id: "l-9",
    customer_id: "c-9",
    status: "new",
    quoted_amount: null,
    project_type: "Concrete Patio",
    project_description: "Interested in a patio. No details yet.",
    assigned_to: null,
    vapi_call_id: null,
    call_transcript_url: null,
    call_duration_seconds: null,
    created_at: "2026-03-15T10:00:00Z",
    updated_at: "2026-03-15T10:00:00Z",
  },
  {
    id: "l-10",
    customer_id: "c-10",
    status: "new",
    quoted_amount: null,
    project_type: "Landscaping",
    project_description:
      "Spring landscaping package + firewood delivery for fall.",
    assigned_to: null,
    vapi_call_id: null,
    call_transcript_url: null,
    call_duration_seconds: null,
    created_at: "2026-03-18T14:00:00Z",
    updated_at: "2026-03-20T08:30:00Z",
  },
  {
    id: "l-11",
    customer_id: "c-11",
    status: "booked",
    quoted_amount: 52000,
    project_type: "Commercial Pole Barn",
    project_description:
      "40x60 pole barn for equipment storage. 14ft sidewalls, 2 large overhead doors, gravel approach.",
    assigned_to: "tm-1",
    vapi_call_id: null,
    call_transcript_url: null,
    call_duration_seconds: null,
    created_at: "2026-02-05T09:00:00Z",
    updated_at: "2026-03-21T11:00:00Z",
  },
  {
    id: "l-12",
    customer_id: "c-12",
    status: "contacted",
    quoted_amount: null,
    project_type: "Curbing + Walkway",
    project_description:
      "Decorative curbing around beds and new concrete walkway to front door.",
    assigned_to: "tm-3",
    vapi_call_id: null,
    call_transcript_url: null,
    call_duration_seconds: null,
    created_at: "2026-03-20T16:00:00Z",
    updated_at: "2026-03-20T16:00:00Z",
  },
  {
    id: "l-13",
    customer_id: "c-2",
    status: "lost",
    quoted_amount: 4500,
    project_type: "Sidewalk Repair",
    project_description:
      "Previous inquiry for sidewalk. Went with another contractor.",
    assigned_to: "tm-2",
    vapi_call_id: null,
    call_transcript_url: null,
    call_duration_seconds: null,
    created_at: "2025-11-10T09:00:00Z",
    updated_at: "2025-12-15T14:00:00Z",
  },
];

export const demoActivities: Activity[] = [
  {
    id: "a-1",
    lead_id: "l-1",
    customer_id: "c-1",
    type: "call",
    description:
      "Initial call with Steve. Discussed stamped patio options and fire pit placement.",
    created_by: "tm-2",
    created_at: "2026-02-10T14:30:00Z",
  },
  {
    id: "a-2",
    lead_id: "l-1",
    customer_id: "c-1",
    type: "quote",
    description: "Sent quote for $8,500 — stamped patio with fire pit.",
    created_by: "tm-2",
    created_at: "2026-02-15T10:00:00Z",
  },
  {
    id: "a-3",
    lead_id: "l-1",
    customer_id: "c-1",
    type: "note",
    description: "Customer approved quote. Deposit received. Scheduled for March.",
    created_by: "tm-2",
    created_at: "2026-02-20T11:30:00Z",
  },
  {
    id: "a-4",
    lead_id: "l-1",
    customer_id: "c-1",
    type: "note",
    description: "Started excavation. Weather looks good for the week.",
    created_by: "tm-1",
    created_at: "2026-03-10T08:00:00Z",
  },
  {
    id: "a-5",
    lead_id: "l-2",
    customer_id: "c-2",
    type: "call",
    description: "Brian called about driveway replacement. Scheduled site visit.",
    created_by: "tm-2",
    created_at: "2026-02-18T10:15:00Z",
  },
  {
    id: "a-6",
    lead_id: "l-2",
    customer_id: "c-2",
    type: "note",
    description: "Site visit completed. Measured 60ft driveway, noted drain issues.",
    created_by: "tm-2",
    created_at: "2026-02-22T14:00:00Z",
  },
  {
    id: "a-7",
    lead_id: "l-2",
    customer_id: "c-2",
    type: "quote",
    description: "Sent quote for $12,200 — driveway tear-out and replace.",
    created_by: "tm-2",
    created_at: "2026-03-01T09:30:00Z",
  },
  {
    id: "a-8",
    lead_id: "l-3",
    customer_id: "c-3",
    type: "email",
    description: "Rachel emailed plans for 30x40 post frame. Reviewed specs.",
    created_by: "tm-1",
    created_at: "2026-01-22T16:45:00Z",
  },
  {
    id: "a-9",
    lead_id: "l-3",
    customer_id: "c-3",
    type: "quote",
    description: "Sent detailed quote for $34,000 — post frame garage.",
    created_by: "tm-1",
    created_at: "2026-02-01T10:00:00Z",
  },
  {
    id: "a-10",
    lead_id: "l-3",
    customer_id: "c-3",
    type: "payment",
    description: "Deposit received — $10,000. Project booked for April.",
    created_by: "tm-1",
    created_at: "2026-03-15T11:00:00Z",
  },
  {
    id: "a-11",
    lead_id: "l-5",
    customer_id: "c-5",
    type: "call",
    description: "Angela called about curbing. Wants to match neighbor's style.",
    created_by: "tm-3",
    created_at: "2026-03-05T13:20:00Z",
  },
  {
    id: "a-12",
    lead_id: "l-5",
    customer_id: "c-5",
    type: "note",
    description: "Scheduled site visit for Friday to measure and pick colors.",
    created_by: "tm-3",
    created_at: "2026-03-12T09:00:00Z",
  },
  {
    id: "a-13",
    lead_id: "l-7",
    customer_id: "c-7",
    type: "quote",
    description: "Sent quote for $18,500 — circular driveway, exposed aggregate.",
    created_by: "tm-1",
    created_at: "2026-03-01T14:00:00Z",
  },
  {
    id: "a-14",
    lead_id: "l-7",
    customer_id: "c-7",
    type: "payment",
    description: "Deposit received — $5,000. Started forming.",
    created_by: "tm-1",
    created_at: "2026-03-10T08:30:00Z",
  },
  {
    id: "a-15",
    lead_id: "l-8",
    customer_id: "c-8",
    type: "note",
    description: "Project complete. Final inspection passed. Customer very happy.",
    created_by: "tm-1",
    created_at: "2026-03-12T09:00:00Z",
  },
  {
    id: "a-16",
    lead_id: "l-8",
    customer_id: "c-8",
    type: "payment",
    description: "Final payment received — $18,000. Project fully paid.",
    created_by: "tm-1",
    created_at: "2026-03-12T15:00:00Z",
  },
  {
    id: "a-17",
    lead_id: "l-11",
    customer_id: "c-11",
    type: "call",
    description:
      "Luis called about large pole barn. Discussed specs and timeline.",
    created_by: "tm-1",
    created_at: "2026-02-05T09:00:00Z",
  },
  {
    id: "a-18",
    lead_id: "l-11",
    customer_id: "c-11",
    type: "quote",
    description: "Sent quote for $52,000 — 40x60 commercial pole barn.",
    created_by: "tm-1",
    created_at: "2026-02-15T10:00:00Z",
  },
  {
    id: "a-19",
    lead_id: "l-11",
    customer_id: "c-11",
    type: "payment",
    description: "Deposit received — $15,000. Booked for late April start.",
    created_by: "tm-1",
    created_at: "2026-03-01T11:00:00Z",
  },
  {
    id: "a-20",
    lead_id: "l-4",
    customer_id: "c-4",
    type: "call",
    description: "Diane called about backyard renovation. Wants full package.",
    created_by: "tm-2",
    created_at: "2026-03-01T09:00:00Z",
  },
  {
    id: "a-21",
    lead_id: "l-4",
    customer_id: "c-4",
    type: "quote",
    description:
      "Sent quote for $22,500 — retaining wall, patio, landscaping.",
    created_by: "tm-2",
    created_at: "2026-03-15T14:00:00Z",
  },
  {
    id: "a-22",
    lead_id: "l-4",
    customer_id: "c-4",
    type: "email",
    description: "Follow-up email sent. Waiting for approval on quote.",
    created_by: "tm-2",
    created_at: "2026-03-22T10:00:00Z",
  },
];

export const demoEstimates: Estimate[] = [
  {
    id: "est-1",
    customer_id: "c-1",
    customer_name: "Steve & Linda Morales",
    status: "accepted",
    project_type: "Stamped Concrete",
    dimensions: { length: 20, width: 16, square_footage: 320 },
    materials: ["Ashlar Slate"],
    complexity: "moderate",
    options: {
      demolition: false,
      grading: true,
      sealing: true,
      color_stain: "Desert Tan with Dark Walnut Release",
    },
    line_items: [
      {
        id: "li-1",
        category: "material",
        description: "Concrete (6-sack mix) — 320 sq ft at 4\" depth",
        quantity: 4,
        unit: "yards",
        unit_cost: 165,
        total: 660,
      },
      {
        id: "li-2",
        category: "material",
        description: "Ashlar Slate stamp mats & color hardener",
        quantity: 1,
        unit: "set",
        unit_cost: 480,
        total: 480,
      },
      {
        id: "li-3",
        category: "material",
        description: "Rebar & mesh reinforcement",
        quantity: 320,
        unit: "sq ft",
        unit_cost: 1.25,
        total: 400,
      },
      {
        id: "li-4",
        category: "material",
        description: "Acrylic sealer (2 coats)",
        quantity: 5,
        unit: "gallons",
        unit_cost: 45,
        total: 225,
      },
      {
        id: "li-5",
        category: "labor",
        description: "Excavation & grading",
        quantity: 8,
        unit: "hours",
        unit_cost: 65,
        total: 520,
      },
      {
        id: "li-6",
        category: "labor",
        description: "Forming, pouring & stamping",
        quantity: 24,
        unit: "hours",
        unit_cost: 65,
        total: 1560,
      },
      {
        id: "li-7",
        category: "labor",
        description: "Finishing & sealing",
        quantity: 8,
        unit: "hours",
        unit_cost: 65,
        total: 520,
      },
      {
        id: "li-8",
        category: "equipment",
        description: "Skid steer rental (1 day)",
        quantity: 1,
        unit: "day",
        unit_cost: 350,
        total: 350,
      },
      {
        id: "li-9",
        category: "equipment",
        description: "Concrete pump truck",
        quantity: 1,
        unit: "trip",
        unit_cost: 450,
        total: 450,
      },
    ],
    subtotal: 5165,
    margin: 1291,
    total: 6456,
    timeline: "3-4 days on site, weather permitting",
    notes:
      "Includes fire pit cutout. Customer providing fire pit insert. Color samples approved.",
    created_at: "2026-02-14T10:00:00Z",
    updated_at: "2026-02-20T11:30:00Z",
  },
  {
    id: "est-2",
    customer_id: "c-2",
    customer_name: "Brian Whitfield",
    status: "sent",
    project_type: "Concrete Driveway",
    dimensions: { length: 60, width: 12, depth: 6, square_footage: 720 },
    materials: ["Broom Finish"],
    complexity: "moderate",
    options: {
      demolition: true,
      grading: true,
      sealing: false,
      color_stain: "",
    },
    line_items: [
      {
        id: "li-10",
        category: "material",
        description: "Concrete (6-sack mix) — 720 sq ft at 6\" depth",
        quantity: 14,
        unit: "yards",
        unit_cost: 165,
        total: 2310,
      },
      {
        id: "li-11",
        category: "material",
        description: "Rebar grid (#4 rebar, 18\" OC)",
        quantity: 720,
        unit: "sq ft",
        unit_cost: 1.5,
        total: 1080,
      },
      {
        id: "li-12",
        category: "labor",
        description: "Demolition & haul-off of existing driveway",
        quantity: 16,
        unit: "hours",
        unit_cost: 65,
        total: 1040,
      },
      {
        id: "li-13",
        category: "labor",
        description: "Grading & compaction",
        quantity: 8,
        unit: "hours",
        unit_cost: 65,
        total: 520,
      },
      {
        id: "li-14",
        category: "labor",
        description: "Forming, pouring & finishing",
        quantity: 24,
        unit: "hours",
        unit_cost: 65,
        total: 1560,
      },
      {
        id: "li-15",
        category: "equipment",
        description: "Skid steer + dump trailer (2 days)",
        quantity: 2,
        unit: "days",
        unit_cost: 450,
        total: 900,
      },
      {
        id: "li-16",
        category: "equipment",
        description: "Concrete pump truck",
        quantity: 1,
        unit: "trip",
        unit_cost: 450,
        total: 450,
      },
    ],
    subtotal: 7860,
    margin: 1965,
    total: 9825,
    timeline: "4-5 days including demo and cure time",
    notes: "Drain issue noted at site visit — may need to adjust grade.",
    created_at: "2026-03-01T09:30:00Z",
    updated_at: "2026-03-01T09:30:00Z",
  },
  {
    id: "est-3",
    customer_id: "c-5",
    customer_name: "Angela Ross",
    status: "draft",
    project_type: "Decorative Curbing",
    dimensions: { linear_feet: 120 },
    materials: ["Mower Edge"],
    complexity: "easy",
    options: {
      demolition: false,
      grading: false,
      sealing: true,
      color_stain: "Charcoal Gray",
    },
    line_items: [
      {
        id: "li-17",
        category: "material",
        description: "Curbing mix & color additive",
        quantity: 120,
        unit: "linear ft",
        unit_cost: 2.5,
        total: 300,
      },
      {
        id: "li-18",
        category: "material",
        description: "Sealer",
        quantity: 2,
        unit: "gallons",
        unit_cost: 45,
        total: 90,
      },
      {
        id: "li-19",
        category: "labor",
        description: "Layout, extrude & finish curbing",
        quantity: 10,
        unit: "hours",
        unit_cost: 65,
        total: 650,
      },
      {
        id: "li-20",
        category: "equipment",
        description: "Curbing machine",
        quantity: 1,
        unit: "day",
        unit_cost: 200,
        total: 200,
      },
    ],
    subtotal: 1240,
    margin: 310,
    total: 1550,
    timeline: "1 day on site",
    notes: "Customer wants to match neighbor's curbing style.",
    created_at: "2026-03-18T14:00:00Z",
    updated_at: "2026-03-18T14:00:00Z",
  },
  {
    id: "est-4",
    customer_id: "c-4",
    customer_name: "Tom & Diane Marshall",
    status: "sent",
    project_type: "Landscaping",
    dimensions: { square_footage: 2400 },
    materials: ["Retaining Walls", "Mulch Beds", "Plantings & Shrubs"],
    complexity: "difficult",
    options: {
      demolition: false,
      grading: true,
      sealing: false,
      color_stain: "",
    },
    line_items: [
      {
        id: "li-21",
        category: "material",
        description: "Retaining wall blocks (45 linear ft, 3 courses)",
        quantity: 540,
        unit: "blocks",
        unit_cost: 4.5,
        total: 2430,
      },
      {
        id: "li-22",
        category: "material",
        description: "Mulch (hardwood)",
        quantity: 15,
        unit: "yards",
        unit_cost: 55,
        total: 825,
      },
      {
        id: "li-23",
        category: "material",
        description: "Plants, shrubs & perennials",
        quantity: 1,
        unit: "lot",
        unit_cost: 2800,
        total: 2800,
      },
      {
        id: "li-24",
        category: "material",
        description: "Landscape fabric & edging",
        quantity: 1,
        unit: "lot",
        unit_cost: 350,
        total: 350,
      },
      {
        id: "li-25",
        category: "labor",
        description: "Grading & site prep",
        quantity: 16,
        unit: "hours",
        unit_cost: 65,
        total: 1040,
      },
      {
        id: "li-26",
        category: "labor",
        description: "Retaining wall construction",
        quantity: 32,
        unit: "hours",
        unit_cost: 65,
        total: 2080,
      },
      {
        id: "li-27",
        category: "labor",
        description: "Planting & mulching",
        quantity: 16,
        unit: "hours",
        unit_cost: 65,
        total: 1040,
      },
      {
        id: "li-28",
        category: "equipment",
        description: "Mini excavator rental (2 days)",
        quantity: 2,
        unit: "days",
        unit_cost: 400,
        total: 800,
      },
    ],
    subtotal: 11365,
    margin: 2841,
    total: 14206,
    timeline: "7-10 days depending on weather",
    notes:
      "Full backyard renovation. Includes 15x20 patio area prep (patio quoted separately).",
    created_at: "2026-03-15T14:00:00Z",
    updated_at: "2026-03-15T14:00:00Z",
  },
];

export const demoVisionProjects: VisionProject[] = [
  {
    id: "vis-1",
    customer_id: "c-1",
    customer_name: "Steve & Linda Morales",
    original_image_url: "/demo/vision-backyard-before.jpg",
    service_type: "Stamped Concrete",
    description: "Stamped concrete patio with fire pit in backyard",
    iterations: [
      {
        id: "vi-1",
        image_url: "/demo/vision-backyard-after-1.jpg",
        prompt_used:
          "Professional architectural visualization of a stamped concrete patio with ashlar slate pattern and integrated fire pit installed in this backyard space.",
        add_on: null,
        created_at: "2026-02-12T10:00:00Z",
      },
      {
        id: "vi-2",
        image_url: "/demo/vision-backyard-after-2.jpg",
        prompt_used:
          "Same patio visualization with landscape lighting along the edges and pathway lights.",
        add_on: "Landscape lighting",
        created_at: "2026-02-12T10:15:00Z",
      },
    ],
    created_at: "2026-02-12T10:00:00Z",
    updated_at: "2026-02-12T10:15:00Z",
  },
  {
    id: "vis-2",
    customer_id: "c-4",
    customer_name: "Tom & Diane Marshall",
    original_image_url: "/demo/vision-landscape-before.jpg",
    service_type: "Landscaping",
    description: "Full backyard renovation with retaining wall and patio",
    iterations: [
      {
        id: "vi-3",
        image_url: "/demo/vision-landscape-after-1.jpg",
        prompt_used:
          "Professional landscape design visualization showing retaining wall, patio area, and garden beds in this backyard.",
        add_on: null,
        created_at: "2026-03-02T14:00:00Z",
      },
    ],
    created_at: "2026-03-02T14:00:00Z",
    updated_at: "2026-03-02T14:00:00Z",
  },
];

// ── Module 4: Invoices & Payments ──

export const demoInvoices: Invoice[] = [
  {
    id: "inv-1",
    customer_id: "c-8",
    lead_id: "l-8",
    estimate_id: "est-1",
    invoice_number: "TFT-0001",
    status: "paid",
    line_items: [
      {
        id: "ili-1",
        description: "Post Frame Workshop — 24x30 with lean-to",
        quantity: 1,
        unit_price: 28000,
        total: 28000,
      },
    ],
    subtotal: 28000,
    tax_rate: 0.07,
    tax_amount: 1960,
    total: 29960,
    notes: "Final payment for completed workshop build. Thank you for your business!",
    due_date: "2026-03-15T00:00:00Z",
    sent_at: "2026-03-12T10:00:00Z",
    viewed_at: "2026-03-12T14:22:00Z",
    paid_at: "2026-03-12T15:00:00Z",
    payment_method: "stripe",
    stripe_payment_intent_id: "pi_demo_001",
    created_at: "2026-03-12T09:30:00Z",
    updated_at: "2026-03-12T15:00:00Z",
  },
  {
    id: "inv-2",
    customer_id: "c-3",
    lead_id: "l-3",
    estimate_id: null,
    invoice_number: "TFT-0002",
    status: "sent",
    line_items: [
      {
        id: "ili-2",
        description: "Post Frame Garage 30x40 — Deposit",
        quantity: 1,
        unit_price: 10000,
        total: 10000,
      },
    ],
    subtotal: 10000,
    tax_rate: 0.07,
    tax_amount: 700,
    total: 10700,
    notes: "50% deposit required before project start. Balance due upon completion.",
    due_date: "2026-04-01T00:00:00Z",
    sent_at: "2026-03-20T09:00:00Z",
    viewed_at: null,
    paid_at: null,
    payment_method: null,
    stripe_payment_intent_id: null,
    created_at: "2026-03-20T08:45:00Z",
    updated_at: "2026-03-20T09:00:00Z",
  },
  {
    id: "inv-3",
    customer_id: "c-7",
    lead_id: "l-7",
    estimate_id: null,
    invoice_number: "TFT-0003",
    status: "viewed",
    line_items: [
      {
        id: "ili-3",
        description: "Circular Driveway — Exposed aggregate finish",
        quantity: 1800,
        unit_price: 8.5,
        total: 15300,
      },
      {
        id: "ili-4",
        description: "Turnaround area — additional forming & pour",
        quantity: 1,
        unit_price: 3200,
        total: 3200,
      },
    ],
    subtotal: 18500,
    tax_rate: 0.07,
    tax_amount: 1295,
    total: 19795,
    notes: "Balance due for circular driveway project. Deposit of $5,000 already received.",
    due_date: "2026-04-05T00:00:00Z",
    sent_at: "2026-03-19T16:30:00Z",
    viewed_at: "2026-03-20T08:15:00Z",
    paid_at: null,
    payment_method: null,
    stripe_payment_intent_id: null,
    created_at: "2026-03-19T16:00:00Z",
    updated_at: "2026-03-20T08:15:00Z",
  },
  {
    id: "inv-4",
    customer_id: "c-11",
    lead_id: "l-11",
    estimate_id: null,
    invoice_number: "TFT-0004",
    status: "overdue",
    line_items: [
      {
        id: "ili-5",
        description: "Commercial Pole Barn 40x60 — Deposit (30%)",
        quantity: 1,
        unit_price: 15600,
        total: 15600,
      },
    ],
    subtotal: 15600,
    tax_rate: 0.07,
    tax_amount: 1092,
    total: 16692,
    notes: "Deposit invoice for 40x60 commercial pole barn. Please remit payment to begin material ordering.",
    due_date: "2026-03-15T00:00:00Z",
    sent_at: "2026-03-05T10:00:00Z",
    viewed_at: "2026-03-05T18:30:00Z",
    paid_at: null,
    payment_method: null,
    stripe_payment_intent_id: null,
    created_at: "2026-03-05T09:30:00Z",
    updated_at: "2026-03-05T18:30:00Z",
  },
  {
    id: "inv-5",
    customer_id: "c-1",
    lead_id: "l-1",
    estimate_id: "est-1",
    invoice_number: "TFT-0005",
    status: "partial",
    line_items: [
      {
        id: "ili-6",
        description: "Stamped Concrete Patio — Ashlar Slate pattern, 320 sq ft",
        quantity: 320,
        unit_price: 18.75,
        total: 6000,
      },
      {
        id: "ili-7",
        description: "Fire pit cutout & prep",
        quantity: 1,
        unit_price: 1200,
        total: 1200,
      },
      {
        id: "ili-8",
        description: "Acrylic sealer (2 coats)",
        quantity: 1,
        unit_price: 800,
        total: 800,
      },
    ],
    subtotal: 8000,
    tax_rate: 0.07,
    tax_amount: 560,
    total: 8560,
    notes: "Deposit of $3,000 received. Remaining balance due upon completion.",
    due_date: "2026-03-30T00:00:00Z",
    sent_at: "2026-03-10T11:00:00Z",
    viewed_at: "2026-03-10T14:00:00Z",
    paid_at: null,
    payment_method: null,
    stripe_payment_intent_id: null,
    created_at: "2026-03-10T10:30:00Z",
    updated_at: "2026-03-10T14:00:00Z",
  },
  {
    id: "inv-6",
    customer_id: "c-2",
    lead_id: "l-2",
    estimate_id: "est-2",
    invoice_number: "TFT-0006",
    status: "draft",
    line_items: [
      {
        id: "ili-9",
        description: "Driveway Tear-out & Replace — 720 sq ft, 6\" pour",
        quantity: 1,
        unit_price: 12200,
        total: 12200,
      },
    ],
    subtotal: 12200,
    tax_rate: 0.07,
    tax_amount: 854,
    total: 13054,
    notes: "Pending customer approval of quote. Draft invoice prepared.",
    due_date: "2026-04-15T00:00:00Z",
    sent_at: null,
    viewed_at: null,
    paid_at: null,
    payment_method: null,
    stripe_payment_intent_id: null,
    created_at: "2026-03-22T14:00:00Z",
    updated_at: "2026-03-22T14:00:00Z",
  },
];

export const demoPayments: Payment[] = [
  {
    id: "pay-1",
    invoice_id: "inv-1",
    amount: 29960,
    method: "stripe",
    stripe_payment_id: "ch_demo_001",
    notes: "Full payment via Stripe",
    created_at: "2026-03-12T15:00:00Z",
  },
  {
    id: "pay-2",
    invoice_id: "inv-5",
    amount: 3000,
    method: "check",
    stripe_payment_id: null,
    notes: "Deposit — check #4821",
    created_at: "2026-03-10T16:00:00Z",
  },
];

// ── Module 5: AI Agents ──

export const demoAgents: AIAgent[] = [
  {
    id: "agent-1",
    name: "Lead Follow-Up Agent",
    type: "lead_followup",
    description:
      "Monitors new leads that haven't been contacted within 24 hours. Automatically drafts a follow-up email or SMS for team review.",
    status: "active",
    config: {
      wait_hours: 24,
      escalate_after_days: 3,
      approval_mode: "requires_approval",
      message_template:
        "Hi {{first_name}},\n\nThank you for reaching out to The Finishing Touch! We received your inquiry about {{project_type}} and would love to discuss your project.\n\nWould you be available for a quick call this week? We can go over your vision, provide a free estimate, and answer any questions.\n\nBest regards,\nThe Finishing Touch Team\n(765) 555-0100",
    },
    last_run: "2026-03-24T08:00:00Z",
    actions_today: 3,
    actions_this_week: 12,
    created_at: "2026-02-01T00:00:00Z",
  },
  {
    id: "agent-2",
    name: "Quote Follow-Up Agent",
    type: "quote_followup",
    description:
      "Monitors leads in 'quoted' status that haven't responded in 3 days. Drafts a gentle nudge email. Escalates to team after 7 days.",
    status: "active",
    config: {
      wait_hours: 72,
      escalate_after_days: 7,
      approval_mode: "auto_send",
      message_template:
        "Hi {{first_name}},\n\nJust checking in on the estimate we sent over for your {{project_type}} project. We want to make sure you have everything you need to make a decision.\n\nIf you have any questions or would like to discuss adjustments, we're happy to help!\n\nBest,\nThe Finishing Touch Team",
    },
    last_run: "2026-03-24T08:00:00Z",
    actions_today: 1,
    actions_this_week: 5,
    created_at: "2026-02-01T00:00:00Z",
  },
  {
    id: "agent-3",
    name: "Review Request Agent",
    type: "review_request",
    description:
      "Triggers when a lead moves to 'completed' status. Waits 3 days then sends a Google review request. Follows up once after 7 days.",
    status: "active",
    config: {
      wait_hours: 72,
      escalate_after_days: 7,
      approval_mode: "auto_send",
      message_template:
        "Hi {{first_name}},\n\nWe hope you're enjoying your new {{project_type}}! It was a pleasure working with you.\n\nWould you mind leaving us a quick Google review? It helps other homeowners find us and means a lot to our small team.\n\n⭐ Leave a review: https://g.page/thefinishingtouchllc/review\n\nThank you!\nThe Finishing Touch Team",
    },
    last_run: "2026-03-24T08:00:00Z",
    actions_today: 0,
    actions_this_week: 2,
    created_at: "2026-02-01T00:00:00Z",
  },
  {
    id: "agent-4",
    name: "Website Chatbot",
    type: "website_chatbot",
    description:
      "Answers common questions on thefinishingtouchllc.com — pricing, service area, scheduling, and services. Captures lead info and creates CRM leads.",
    status: "paused",
    config: {
      wait_hours: 0,
      escalate_after_days: 0,
      approval_mode: "auto_send",
      message_template:
        "Welcome to The Finishing Touch! I can help with questions about our concrete, landscaping, and post frame services. How can I help you today?",
    },
    last_run: "2026-03-23T22:15:00Z",
    actions_today: 0,
    actions_this_week: 8,
    created_at: "2026-02-15T00:00:00Z",
  },
];

export const demoAgentActions: AgentAction[] = [
  {
    id: "aa-1",
    agent_id: "agent-1",
    customer_id: "c-9",
    lead_id: "l-9",
    action_type: "email_sent",
    description: "Sent follow-up email to Mark Stevenson — new lead, no contact in 24h.",
    status: "completed",
    created_at: "2026-03-24T08:05:00Z",
  },
  {
    id: "aa-2",
    agent_id: "agent-1",
    customer_id: "c-10",
    lead_id: "l-10",
    action_type: "email_sent",
    description: "Sent follow-up email to Sarah & Dave Henning — new lead, no contact in 24h.",
    status: "completed",
    created_at: "2026-03-24T08:06:00Z",
  },
  {
    id: "aa-3",
    agent_id: "agent-1",
    customer_id: "c-6",
    lead_id: "l-6",
    action_type: "email_sent",
    description: "Drafted follow-up for Derek Johnson — awaiting approval.",
    status: "pending_approval",
    created_at: "2026-03-24T08:07:00Z",
  },
  {
    id: "aa-4",
    agent_id: "agent-2",
    customer_id: "c-2",
    lead_id: "l-2",
    action_type: "email_sent",
    description: "Sent quote follow-up to Brian Whitfield — quoted 3+ days ago.",
    status: "completed",
    created_at: "2026-03-24T08:10:00Z",
  },
  {
    id: "aa-5",
    agent_id: "agent-2",
    customer_id: "c-5",
    lead_id: "l-5",
    action_type: "escalated",
    description: "Escalated Angela Ross — no response after 7 days on quote.",
    status: "completed",
    created_at: "2026-03-23T08:10:00Z",
  },
  {
    id: "aa-6",
    agent_id: "agent-3",
    customer_id: "c-8",
    lead_id: "l-8",
    action_type: "review_requested",
    description: "Sent Google review request to Patricia Okonkwo — project completed.",
    status: "completed",
    created_at: "2026-03-22T08:00:00Z",
  },
  {
    id: "aa-7",
    agent_id: "agent-3",
    customer_id: "c-8",
    lead_id: "l-8",
    action_type: "review_requested",
    description: "Sent follow-up review request to Patricia Okonkwo — no review after 7 days.",
    status: "completed",
    created_at: "2026-03-22T08:00:00Z",
  },
  {
    id: "aa-8",
    agent_id: "agent-4",
    customer_id: "c-12",
    lead_id: null,
    action_type: "lead_created",
    description: "Chatbot created new lead from website visitor: Jason Turner — Concrete Patio inquiry.",
    status: "completed",
    created_at: "2026-03-23T14:30:00Z",
  },
  {
    id: "aa-9",
    agent_id: "agent-1",
    customer_id: "c-12",
    lead_id: "l-13",
    action_type: "email_sent",
    description: "Sent follow-up email to Jason Turner — new chatbot lead, no contact in 24h.",
    status: "pending_approval",
    created_at: "2026-03-24T08:08:00Z",
  },
  {
    id: "aa-10",
    agent_id: "agent-2",
    customer_id: "c-4",
    lead_id: "l-4",
    action_type: "email_sent",
    description: "Sent quote follow-up to Tom & Diane Marshall — quoted 7+ days ago.",
    status: "completed",
    created_at: "2026-03-22T08:15:00Z",
  },
];

// ── Module 6: Email Marketing ──

export const demoMarketingContacts: MarketingContact[] = [
  { id: "mc-1", customer_id: "c-1", name: "Steve & Linda Morales", email: "smorales@gmail.com", tags: ["past-customer", "concrete", "stamped-concrete"], subscribed: true, created_at: "2026-02-10T14:30:00Z" },
  { id: "mc-2", customer_id: "c-2", name: "Brian Whitfield", email: "bwhitfield@yahoo.com", tags: ["active-lead", "concrete", "driveway"], subscribed: true, created_at: "2026-02-18T10:15:00Z" },
  { id: "mc-3", customer_id: "c-3", name: "Rachel Kim", email: "rachelk@outlook.com", tags: ["active-lead", "post-frame"], subscribed: true, created_at: "2026-01-22T16:45:00Z" },
  { id: "mc-4", customer_id: "c-4", name: "Tom & Diane Marshall", email: "tmarshall@gmail.com", tags: ["active-lead", "landscaping"], subscribed: true, created_at: "2026-03-01T09:00:00Z" },
  { id: "mc-5", customer_id: "c-5", name: "Angela Ross", email: "aross@icloud.com", tags: ["active-lead", "curbing"], subscribed: true, created_at: "2026-03-05T13:20:00Z" },
  { id: "mc-6", customer_id: "c-6", name: "Derek Johnson", email: "djohnson@gmail.com", tags: ["new-lead", "concrete"], subscribed: true, created_at: "2026-03-08T11:00:00Z" },
  { id: "mc-7", customer_id: "c-7", name: "Carla & Jim Nesbitt", email: "cnesbitt@gmail.com", tags: ["active-lead", "driveway", "premium"], subscribed: true, created_at: "2026-02-25T08:30:00Z" },
  { id: "mc-8", customer_id: "c-8", name: "Patricia Okonkwo", email: "pokonkwo@hotmail.com", tags: ["past-customer", "post-frame"], subscribed: true, created_at: "2026-01-30T15:00:00Z" },
  { id: "mc-9", customer_id: "c-9", name: "Mark Stevenson", email: "mstevenson@gmail.com", tags: ["new-lead", "concrete"], subscribed: true, created_at: "2026-03-15T10:00:00Z" },
  { id: "mc-10", customer_id: "c-10", name: "Sarah & Dave Henning", email: "shenning@gmail.com", tags: ["new-lead", "landscaping", "firewood"], subscribed: true, created_at: "2026-03-18T14:00:00Z" },
  { id: "mc-11", customer_id: "c-11", name: "Luis Hernandez", email: "lhernandez@yahoo.com", tags: ["active-lead", "post-frame", "commercial"], subscribed: false, created_at: "2026-02-05T09:00:00Z" },
  { id: "mc-12", customer_id: "c-12", name: "Jason Turner", email: "jturner@gmail.com", tags: ["new-lead", "concrete", "chatbot"], subscribed: true, created_at: "2026-03-23T14:30:00Z" },
];

export const demoEmailTemplates: EmailTemplate[] = [
  {
    id: "tpl-1",
    name: "Spring Season Kickoff",
    subject: "Spring is here! Book your outdoor project with The Finishing Touch",
    body: "Hi {{first_name}},\n\nSpring is right around the corner, and it's the perfect time to start planning your outdoor project!\n\nWhether you're dreaming of a new stamped concrete patio, a fresh driveway, or a beautiful landscape makeover — we're ready to bring your vision to life.\n\n🌿 Book before April 15 and get 10% off your project!\n\nReply to this email or call us at (765) 555-0100 to schedule your free estimate.\n\nBest,\nThe Finishing Touch Team",
    category: "seasonal_promo",
    merge_fields: ["first_name"],
    created_at: "2026-02-20T10:00:00Z",
    updated_at: "2026-03-01T09:00:00Z",
  },
  {
    id: "tpl-2",
    name: "New Service: Decorative Curbing",
    subject: "NEW! Decorative Curbing now available from The Finishing Touch",
    body: "Hi {{first_name}},\n\nExciting news — we've added Decorative Curbing to our service lineup!\n\nGive your landscape beds a clean, professional edge with our custom concrete curbing. Available in multiple styles and colors to match your home.\n\nStarting at just $8/linear foot installed.\n\nInterested? Reply to this email or visit our website to learn more.\n\nCheers,\nThe Finishing Touch Team",
    category: "new_service",
    merge_fields: ["first_name"],
    created_at: "2026-03-01T10:00:00Z",
    updated_at: "2026-03-01T10:00:00Z",
  },
  {
    id: "tpl-3",
    name: "Project Showcase: Stamped Patio",
    subject: "See what we built: Stunning stamped concrete patio in Greentown",
    body: "Hi {{first_name}},\n\nCheck out our latest project — a beautiful ashlar slate stamped concrete patio with an integrated fire pit, built right here in Greentown.\n\nThe homeowner wanted an outdoor living space that felt like an extension of their home, and we delivered!\n\n📸 Want to see what we can do for you? Schedule a free consultation today.\n\nCall (765) 555-0100 or reply to this email.\n\nThe Finishing Touch Team",
    category: "project_showcase",
    merge_fields: ["first_name"],
    created_at: "2026-03-10T10:00:00Z",
    updated_at: "2026-03-10T10:00:00Z",
  },
  {
    id: "tpl-4",
    name: "Review Request",
    subject: "How did we do? Leave us a Google review!",
    body: "Hi {{first_name}},\n\nThank you for choosing The Finishing Touch for your {{project_type}} project!\n\nWe hope everything looks great. If you have a moment, we'd really appreciate a quick Google review. It helps other homeowners in Howard County find us.\n\n⭐ Leave a review: https://g.page/thefinishingtouchllc/review\n\nThank you for your support!\nThe Finishing Touch Team",
    category: "review_request",
    merge_fields: ["first_name", "project_type"],
    created_at: "2026-02-01T10:00:00Z",
    updated_at: "2026-02-01T10:00:00Z",
  },
];

export const demoCampaigns: Campaign[] = [
  {
    id: "camp-1",
    name: "Spring 2026 Kickoff",
    template_id: "tpl-1",
    segment_tags: ["past-customer"],
    status: "sent",
    scheduled_at: "2026-03-01T10:00:00Z",
    sent_at: "2026-03-01T10:00:00Z",
    recipients_count: 2,
    opens: 2,
    clicks: 1,
    unsubscribes: 0,
    created_at: "2026-02-25T10:00:00Z",
    updated_at: "2026-03-01T10:00:00Z",
  },
  {
    id: "camp-2",
    name: "Curbing Service Launch",
    template_id: "tpl-2",
    segment_tags: ["past-customer", "active-lead"],
    status: "sent",
    scheduled_at: "2026-03-05T09:00:00Z",
    sent_at: "2026-03-05T09:00:00Z",
    recipients_count: 8,
    opens: 5,
    clicks: 2,
    unsubscribes: 1,
    created_at: "2026-03-03T10:00:00Z",
    updated_at: "2026-03-05T09:00:00Z",
  },
  {
    id: "camp-3",
    name: "March Project Showcase",
    template_id: "tpl-3",
    segment_tags: ["new-lead", "concrete"],
    status: "scheduled",
    scheduled_at: "2026-03-25T10:00:00Z",
    sent_at: null,
    recipients_count: 3,
    opens: 0,
    clicks: 0,
    unsubscribes: 0,
    created_at: "2026-03-20T10:00:00Z",
    updated_at: "2026-03-20T10:00:00Z",
  },
  {
    id: "camp-4",
    name: "Summer Booking Push",
    template_id: "tpl-1",
    segment_tags: [],
    status: "draft",
    scheduled_at: null,
    sent_at: null,
    recipients_count: 0,
    opens: 0,
    clicks: 0,
    unsubscribes: 0,
    created_at: "2026-03-22T14:00:00Z",
    updated_at: "2026-03-22T14:00:00Z",
  },
];

export const demoAutomations: Automation[] = [
  {
    id: "auto-1",
    name: "New Lead Welcome",
    description: "Welcomes new leads with a 3-email sequence over 2 weeks introducing TFT services.",
    trigger: "New lead created in CRM",
    status: "active",
    emails: [
      { id: "ae-1", subject: "Welcome to The Finishing Touch!", body: "Hi {{first_name}}, thanks for reaching out! We specialize in concrete, landscaping, and post frame construction in Howard County and surrounding areas...", delay_days: 0 },
      { id: "ae-2", subject: "What sets The Finishing Touch apart", body: "Hi {{first_name}}, we wanted to share a bit about why homeowners choose us — quality craftsmanship, transparent pricing, and a team that treats your property like our own...", delay_days: 5 },
      { id: "ae-3", subject: "Ready to get started? Let's schedule your free estimate", body: "Hi {{first_name}}, we'd love to give you a free, no-obligation estimate for your project. Just reply to this email or call us at (765) 555-0100...", delay_days: 14 },
    ],
    enrolled_count: 6,
    completed_count: 3,
    created_at: "2026-02-01T00:00:00Z",
  },
  {
    id: "auto-2",
    name: "Post-Quote Follow-Up",
    description: "Follows up with leads who have received a quote but haven't responded.",
    trigger: "Lead moved to 'quoted' status",
    status: "active",
    emails: [
      { id: "ae-4", subject: "Your estimate from The Finishing Touch", body: "Hi {{first_name}}, just wanted to make sure you received the estimate for your {{project_type}} project. Let us know if you have any questions...", delay_days: 3 },
      { id: "ae-5", subject: "Still thinking it over? We're here to help", body: "Hi {{first_name}}, no rush — we know these are big decisions. If cost is a factor, we're happy to explore options that fit your budget...", delay_days: 7 },
    ],
    enrolled_count: 4,
    completed_count: 2,
    created_at: "2026-02-01T00:00:00Z",
  },
  {
    id: "auto-3",
    name: "Post-Project Thank You + Review",
    description: "Thanks customers after project completion and asks for a Google review.",
    trigger: "Lead moved to 'completed' status",
    status: "active",
    emails: [
      { id: "ae-6", subject: "Thank you for choosing The Finishing Touch!", body: "Hi {{first_name}}, we truly appreciate you trusting us with your {{project_type}} project. We hope the finished result exceeded your expectations...", delay_days: 1 },
      { id: "ae-7", subject: "Mind leaving us a quick review?", body: "Hi {{first_name}}, if you're enjoying your new {{project_type}}, we'd appreciate a quick Google review. It helps us reach more homeowners like you...", delay_days: 14 },
    ],
    enrolled_count: 2,
    completed_count: 1,
    created_at: "2026-02-01T00:00:00Z",
  },
  {
    id: "auto-4",
    name: "Seasonal Reactivation",
    description: "Reaches out to past customers before each season with relevant offers.",
    trigger: "Seasonal (Spring/Fall) — past customers only",
    status: "paused",
    emails: [
      { id: "ae-8", subject: "It's almost {{season}} — time to plan your next project!", body: "Hi {{first_name}}, {{season}} is the perfect time for outdoor projects. As a past customer, you get priority scheduling and 5% off your next project...", delay_days: 0 },
    ],
    enrolled_count: 2,
    completed_count: 0,
    created_at: "2026-02-15T00:00:00Z",
  },
];

export const demoAvailability: AvailabilityRule[] = [
  { id: "ar-1", team_member_id: "tm-1", day_of_week: 1, start_time: "08:00", end_time: "17:00", is_enabled: true },
  { id: "ar-2", team_member_id: "tm-1", day_of_week: 2, start_time: "08:00", end_time: "17:00", is_enabled: true },
  { id: "ar-3", team_member_id: "tm-1", day_of_week: 3, start_time: "08:00", end_time: "17:00", is_enabled: true },
  { id: "ar-4", team_member_id: "tm-1", day_of_week: 4, start_time: "08:00", end_time: "17:00", is_enabled: true },
  { id: "ar-5", team_member_id: "tm-1", day_of_week: 5, start_time: "08:00", end_time: "17:00", is_enabled: true },
];

export const demoCalendarEvents: CalendarEvent[] = [
  {
    id: "evt-1",
    team_member_id: "tm-1",
    type: "quote_visit",
    status: "scheduled",
    title: "Quote: Steve & Linda Morales",
    description: null,
    start_time: new Date(Date.now() + 86400000 * 2).toISOString().split("T")[0] + "T18:00:00Z",
    end_time: new Date(Date.now() + 86400000 * 2).toISOString().split("T")[0] + "T19:00:00Z",
    customer_name: "Steve & Linda Morales",
    customer_phone: "(765) 555-0101",
    customer_address: "1234 Oak St, Greentown, IN",
    service_type: "Concrete Patio",
    project_description: "20x20 stamped patio with fire pit pad",
    created_by: "agent",
    lead_id: "l-1",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "evt-2",
    team_member_id: "tm-1",
    type: "quote_visit",
    status: "scheduled",
    title: "Quote: Brian Whitfield",
    description: null,
    start_time: new Date(Date.now() + 86400000 * 3).toISOString().split("T")[0] + "T15:00:00Z",
    end_time: new Date(Date.now() + 86400000 * 3).toISOString().split("T")[0] + "T16:00:00Z",
    customer_name: "Brian Whitfield",
    customer_phone: "(765) 555-0202",
    customer_address: "567 Maple Ave, Kokomo, IN",
    service_type: "Concrete Driveway",
    project_description: "Replace cracked driveway, exposed aggregate finish",
    created_by: "manual",
    lead_id: "l-2",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "evt-3",
    team_member_id: "tm-1",
    type: "blocked",
    status: "scheduled",
    title: "Lunch",
    description: null,
    start_time: new Date(Date.now() + 86400000).toISOString().split("T")[0] + "T16:00:00Z",
    end_time: new Date(Date.now() + 86400000).toISOString().split("T")[0] + "T17:00:00Z",
    customer_name: null,
    customer_phone: null,
    customer_address: null,
    service_type: null,
    project_description: null,
    created_by: "manual",
    lead_id: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// ── Job Walk Demo Data ──

export const demoJobWalks: JobWalk[] = [
  {
    id: "jw-1",
    customer_id: "c-1",
    lead_id: "l-1",
    calendar_event_id: "evt-1",
    estimate_id: null,
    status: "draft",
    measurements: {
      areas: [
        { id: "area-1", name: "Main Patio", length: 20, width: 15, depth: 4 },
        { id: "area-2", name: "Fire Pit Pad", length: 8, width: 8, depth: 6 },
      ],
      linear_feet: null,
      grade: "Slight Slope",
      elevation_change: 6,
    },
    site_conditions: {
      soil_type: "Clay",
      drainage: "Poor",
      access: "Easy",
      existing_surface: "Grass/Sod",
      demolition_required: false,
      demolition_area: null,
      grading_required: true,
      grading_yards: 3,
      obstacles: ["Trees", "Roots"],
      utility_lines: "Located",
      permit_needed: "No",
      notes: "Large oak tree near south edge, roots may be an issue. Customer okay with working around it.",
    },
    customer_preferences: {
      what_they_want: "Stamped patio with fire pit area, want it to wrap around the back of the house. Looking at ashlar slate pattern.",
      material_preference: "Ashlar Slate",
      color_finish: "Desert Brown with Charcoal release",
      timeline: "2 Weeks",
      budget_range: "$5-10K",
      decision_maker: "Yes",
      getting_other_quotes: true,
      other_quotes_count: 2,
      referral_potential: "Hot",
      priority: "hot",
    },
    sketch_url: null,
    voice_note_url: null,
    gps_lat: 40.4774,
    gps_lng: -85.8766,
    weather: { temp: 72, conditions: "Partly Cloudy", recent_rain: false },
    created_at: "2026-03-25T14:30:00Z",
    completed_at: null,
  },
  {
    id: "jw-2",
    customer_id: "c-2",
    lead_id: "l-2",
    calendar_event_id: "evt-2",
    estimate_id: "est-2",
    status: "estimated",
    measurements: {
      areas: [
        { id: "area-3", name: "Driveway", length: 40, width: 16, depth: 4 },
        { id: "area-4", name: "Turnaround", length: 12, width: 12, depth: 4 },
      ],
      linear_feet: null,
      grade: "Flat",
      elevation_change: 0,
    },
    site_conditions: {
      soil_type: "Sandy",
      drainage: "Good",
      access: "Easy",
      existing_surface: "Concrete",
      demolition_required: true,
      demolition_area: 640,
      grading_required: false,
      grading_yards: null,
      obstacles: ["Utilities"],
      utility_lines: "Located",
      permit_needed: "No",
      notes: "Existing driveway has significant cracking. Gas line runs along east side.",
    },
    customer_preferences: {
      what_they_want: "Replace cracked driveway with exposed aggregate finish. Add a turnaround pad near the garage.",
      material_preference: "Exposed Aggregate",
      color_finish: "Natural gray",
      timeline: "1 Month",
      budget_range: "$10-20K",
      decision_maker: "Yes",
      getting_other_quotes: false,
      other_quotes_count: null,
      referral_potential: "Maybe",
      priority: "warm",
    },
    sketch_url: null,
    voice_note_url: null,
    gps_lat: 40.4862,
    gps_lng: -86.1336,
    weather: { temp: 65, conditions: "Sunny", recent_rain: true },
    created_at: "2026-03-20T10:00:00Z",
    completed_at: "2026-03-20T10:45:00Z",
  },
  {
    id: "jw-3",
    customer_id: "c-3",
    lead_id: null,
    calendar_event_id: null,
    estimate_id: null,
    status: "completed",
    measurements: {
      areas: [
        { id: "area-5", name: "Building Pad", length: 40, width: 30, depth: 4 },
      ],
      linear_feet: 140,
      grade: "Moderate Slope",
      elevation_change: 18,
    },
    site_conditions: {
      soil_type: "Clay",
      drainage: "Poor",
      access: "Moderate",
      existing_surface: "Grass/Sod",
      demolition_required: false,
      demolition_area: null,
      grading_required: true,
      grading_yards: 12,
      obstacles: ["Trees", "Fence", "Septic"],
      utility_lines: "Need to Call 811",
      permit_needed: "Yes",
      notes: "Septic field on the north side. Building needs to be setback 25 feet. HOA approval required for building design.",
    },
    customer_preferences: {
      what_they_want: "30x40 post frame garage with concrete floor. Metal roof and siding, wainscot on the front.",
      material_preference: "Metal Roof & Siding",
      color_finish: "Charcoal roof, Sandstone siding",
      timeline: "Spring",
      budget_range: "$20K+",
      decision_maker: "Need to talk to spouse",
      getting_other_quotes: true,
      other_quotes_count: 3,
      referral_potential: "Unlikely",
      priority: "cool",
    },
    sketch_url: null,
    voice_note_url: null,
    gps_lat: 40.0456,
    gps_lng: -86.0086,
    weather: { temp: 58, conditions: "Overcast", recent_rain: true },
    created_at: "2026-03-15T09:00:00Z",
    completed_at: "2026-03-15T09:50:00Z",
  },
];

export const demoJobWalkPhotos: JobWalkPhoto[] = [
  {
    id: "jwp-1",
    job_walk_id: "jw-1",
    photo_url: "/placeholder-photo-1.jpg",
    caption: "Backyard overview from deck",
    category: "Overview",
    annotations: [],
    sort_order: 1,
  },
  {
    id: "jwp-2",
    job_walk_id: "jw-1",
    photo_url: "/placeholder-photo-2.jpg",
    caption: "Oak tree root system near patio edge",
    category: "Obstacle",
    annotations: [],
    sort_order: 2,
  },
  {
    id: "jwp-3",
    job_walk_id: "jw-1",
    photo_url: "/placeholder-photo-3.jpg",
    caption: "Grade change along south side",
    category: "Measurement Reference",
    annotations: [],
    sort_order: 3,
  },
  {
    id: "jwp-4",
    job_walk_id: "jw-2",
    photo_url: "/placeholder-photo-4.jpg",
    caption: "Existing driveway cracking",
    category: "Existing Condition",
    annotations: [],
    sort_order: 1,
  },
  {
    id: "jwp-5",
    job_walk_id: "jw-2",
    photo_url: "/placeholder-photo-5.jpg",
    caption: "Garage approach area",
    category: "Overview",
    annotations: [],
    sort_order: 2,
  },
];
